### PR TITLE
Use FastHTTP in the Golang implementation

### PR DESCRIPTION
**Pull request by xplshn**

### CODE REVIEW

**Comment by antonputra** [comment]
Thanks for the PR, @xplshn. If you can place it in fasthttp-app and keep the original for reference, I'll merge it right away.

**Review by antonputra — CHANGES_REQUESTED** [review]
Please keep original app for reference and create "fasthhp-app"

**Comment by xplshn** [comment]
Sounds good!

**Comment by xplshn** [comment]
> Please keep original app for reference and create "fasthhp-app"

Already addressed :)

**Pull request merged**
