### PR TITLE
feat: Fix improper build command

### PR DESCRIPTION
**Pull request by Uzaaft**
Your https://www.youtube.com/watch?v=VxW0ijXAfOs is not representative and should be taken down imo. Try again with the new dockerfile.

### CODE REVIEW

**Comment by antonputra** [comment]
Thanks for the PR! I'll merge and test in a couple of days. I don't want to mislead people right now.

**Comment by Uzaaft** [comment]
> Thanks for the PR! I'll merge and test in a couple of days. I don't want to mislead people right now.

I get waiting for multiple PRs. But the last part doesnt check out. Your current video is already misleading people...

**Comment by antonputra** [comment]
@Uzaaft If I merge right now, people would assume I tested Zig with the flag you suggested.

**Comment by antonputra** [comment]
I'll collect all the tips I can, including pull requests, over the next 2 or 3 days and will release an updated video if there is a significant improvement, or a YouTube post with the results.

**Comment by Uzaaft** [comment]
> I'll collect all the tips I can, including pull requests, over the next 2 or 3 days and will release an updated video if there is a significant improvement, or a YouTube post with the results.

Then you should add the currect git hash in your url as well so that people know exactly which revision the video is referring to.

**Pull request merged**
