### PR TITLE
lesson 208: set 2 workers is similar to that in rust

### PR DESCRIPTION
**Pull request by hessenar**
I am not a strong expert in zig, but according to the code, actix uses 2 workers (and it seems like 2 threads), I suggest making similar logic for the zig code

### CODE REVIEW

**Comment by antonputra** [comment]
Actually i verified this one, it see only 1 cpu inside the container and uses 1 worker not 2.

"by default this number is equal to the number of physical CPUs"

**Comment by antonputra** [comment]
@hessenar I even tried running this app on a standalone VM, 'm7a.large,' with 2 vCPUs. The problem is that the 2 vCPUs correspond to 1 physical processor with two cores, and the app only sees 1 physical processor, so it starts 1 worker instead of two.

https://browser.geekbench.com/v5/cpu/22475411

**Comment by hessenar** [comment]
in the actix documentation
https://actix.rs/docs/server/#multi-threading 
and in code you set 2
https://github.com/antonputra/tutorials/blob/c4eb063422957ddacde6076f2d41c8ebd19dddf7/lessons/208/actix-app/src/main.rs#L12
the presence of only one core (judging by the description, including here) is not an obstacle to creation a separate application instance to handle requests

**Comment by antonputra** [comment]
@hessenar that's try i probably forgot to remove it after testing

**Review by antonputra — APPROVED** [review]

**Pull request merged**
