### PR TITLE
Fix the case of Transfer-Encoding: chunked

### PR DESCRIPTION
**Pull request by panjf2000**
Sorry, I didn't realize that the case of Transfer-Encoding: chunked is not handled properly.

### CODE REVIEW

**Review by antonputra — APPROVED** [review]
@panjf2000  Thanks! I had an issue with the Postgres connection pool. It was limited to the number of event loops gnet creates on start. Was it fixed as well? Or do I need another approach to handle the connection pool?

**Comment by panjf2000** [comment]
The issue of postgres connection pool has been fixed by the last PR.

**Comment by panjf2000** [comment]
Please hold on merging this PR, I have a new commit pending.

**Comment by antonputra** [comment]
@panjf2000 sure, I'll keep it open.

**Comment by panjf2000** [comment]
I think we're good to go. @antonputra 

BTW, please feel free to reach out to me if you encounter any issues when rerunning the benchmark with the latest code. I'd be glad to help!

**Comment by antonputra** [comment]
@panjf2000 Thanks! I appreciate it!

**Pull request merged**
