### PR TITLE
Update 0-cluster-autoscaler.yaml

### PR DESCRIPTION
**Pull request by shaypi**
This will fix the cluster-autoscaler on eks version v1.22.2

### CODE REVIEW

**Comment by antonputra** [comment]
> This will fix the cluster-autoscaler on eks version v1.22.2

Thanks for PR, what is broken exactly?

**Comment by shaypi** [comment]
> 
When I deployed EKS version 1.22 there was an issue with the ClusterRole(I got some error) and I managed to resolve it by using the fix in the PR.

**Comment by antonputra** [comment]
> > 
> 
> When I deployed EKS version 1.22 there was an issue with the ClusterRole(I got some error) and I managed to resolve it by using the fix in the PR.

Thanks, will verify and merge

**Comment by antonputra** [comment]
Based on the documentation, minor version (major.minor.patch) of cluster autoscaler should match the Kubernetes minor version. That said, new cluster autoscalers may have different requirements (different RBAC permissions maybe needed). I'll close this PR since it relevant only to new 1.22 versions.

**Pull request closed without merging**
