### PR TITLE
Lesson 206: Added ntex as another rust framework to benchmark

### PR DESCRIPTION
**Pull request by GPeaky**
Related to issue #273

### CODE REVIEW

**Comment by GPeaky** [comment]
I have also made a couple of changes in the profile.release, which make the performance considerably better

**Comment by antonputra** [comment]
Thnks @GPeaky I'll take a look tomorrow

**Comment by GPeaky** [comment]
I have also added mimallocator which can greatly improve performance.

**Review by antonputra — APPROVED** [review]
Thanks again, I'll run the test soon

**Pull request merged**
