### PR TITLE
Lesson 203: A bunch of impruvements for rust projects

### PR DESCRIPTION
**Pull request by misterjdrg**

### CODE REVIEW

**Comment by antonputra** [comment]
It's a lot of refactoring, with some reverting back to my original version. Please, instead of updating the v2 version, create a new v3 and keep v2 for future reference and i'll merge it.

**Review by antonputra — CHANGES_REQUESTED** [review]
It's a lot of refactoring, with some reverting back to my original version. Please, instead of updating the v2 version, create a new v3 and keep v2 for future reference and i'll merge it.

**Comment by antonputra** [comment]
@misterjdrg i can move it myself, let me know

**Review by erickcestari — APPROVED** [review]

**Comment by melroy89** [comment]
Even impruvements is spelled wrong in the title.

**Comment by stickyburn** [comment]
Pretty shit PR tbh.

**Pull request closed without merging**
