### PR TITLE
feat: litestar application

### PR DESCRIPTION
**Pull request by NewSouthMjos**
Implemented Litestar framework application.
Used all the current implementation of database and memcache.

Litestar can be run with gunicorn too, for example:
```gunicorn -w 1 -k uvicorn.workers.UvicornWorker litestar_app:app --bind 0.0.0.0:8000```

So, Dockerfile needs to be adjusted

### CODE REVIEW

**Review by antonputra — CHANGES_REQUESTED** [review]
Thanks @NewSouthMjos! Can you please put it in its own folder under the 232 lesson, maybe called 'litestar-app'? It's just easier for me not to get mixed up. Also, if you don't mind, could you add the updated Dockerfile? There's less chance that I'll make a mistake.

**Comment by antonputra** [comment]
Or at least add `Dockerfile.litestar` in the root

**Comment by NewSouthMjos** [comment]
Moved to lesson 232.
Note: litestar use mgspec library. Mgspec currently does not support python 3.13: https://github.com/litestar-org/litestar/issues/3265

Buy now, litestar-app using python 3.12

**Review by antonputra — APPROVED** [review]
Thank you! I'll test it in near future!

**Pull request merged**
